language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer update --prefer-dist $DEPENDENCIES

script:
  - XDEBUG_MODE=coverage php -n -dzend_extension=xdebug vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml --colors

after_script:
  - if [ $TRAVIS_PHP_VERSION = '7.4' ]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi
